#!/usr/bin/env python3

import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch

from tools.source_pipeline import fetch_with_fallbacks, verify_staged_sources


SOURCE_PIPELINE = Path(__file__).resolve().parent.parent / "tools" / "source_pipeline.py"


class SourcePipelineTests(unittest.TestCase):
    def test_uses_upstream_without_touching_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "source"
            with patch("tools.source_pipeline.fetch") as fetch:
                chosen = fetch_with_fallbacks(["https://upstream.example/source", "https://mirror.example/source"], destination)
            self.assertEqual(chosen, "https://upstream.example/source")
            fetch.assert_called_once_with("https://upstream.example/source", destination)

    def test_uses_fallback_only_after_upstream_transport_failure(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "source"
            with patch(
                "tools.source_pipeline.fetch",
                side_effect=[RuntimeError("HTTP Error 418"), None],
            ) as fetch:
                chosen = fetch_with_fallbacks(["https://upstream.example/source", "https://mirror.example/source"], destination)
            self.assertEqual(chosen, "https://mirror.example/source")
            self.assertEqual(fetch.call_count, 2)

    def test_reports_every_failed_url(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "source"
            with patch("tools.source_pipeline.fetch", side_effect=RuntimeError("offline")):
                with self.assertRaisesRegex(RuntimeError, "upstream.example.*mirror.example"):
                    fetch_with_fallbacks(["https://upstream.example/source", "https://mirror.example/source"], destination)

    def test_stages_verified_source_for_packit(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / "upstream.tar.xz"
            source.write_bytes(b"verified source")
            package_dir = root / "packages" / "demo"
            package_dir.mkdir(parents=True)
            config = root / "sources.json"
            config.write_text(
                json.dumps(
                    {
                        "packages": [
                            {
                                "name": "demo",
                                "url": source.as_uri(),
                                "filename": source.name,
                                "sha512": hashlib.sha512(source.read_bytes()).hexdigest(),
                            }
                        ]
                    }
                )
            )

            result = subprocess.run(
                [
                    sys.executable,
                    str(SOURCE_PIPELINE),
                    "demo",
                    "--config",
                    str(config),
                    "--output",
                    str(root / "sources"),
                    "--report-dir",
                    str(root / "reports"),
                    "--stage-into",
                    str(root / "packages"),
                ],
                cwd=root,
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual((package_dir / source.name).read_bytes(), b"verified source")

    def test_rejects_source_overwritten_after_staging(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            package_dir = root / "packages" / "demo"
            package_dir.mkdir(parents=True)
            source = package_dir / "demo-1.0.tar.gz"
            source.write_bytes(b"packit generated archive")
            package = {
                "name": "demo",
                "filename": source.name,
                "sha512": hashlib.sha512(b"verified upstream archive").hexdigest(),
            }

            with self.assertRaisesRegex(ValueError, "SHA-512 mismatch"):
                verify_staged_sources(package, root / "packages")


FAKE_GENERATOR = """\
import pathlib
import shutil
import sys

package, package_dir, out_dir = sys.argv[1], pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
fixture = package_dir / "payload.bin"
shutil.copyfile(fixture, out_dir / f"{package}.tar.xz")
"""


class GeneratedSourcePipelineTests(unittest.TestCase):
    """The generate path: run the locked script, hash-verify the artifact."""

    def run_pipeline(self, root: Path, package: dict):
        package_dir = root / "packages" / package["name"]
        package_dir.mkdir(parents=True)
        payload = b"deterministically generated bytes"
        (package_dir / "payload.bin").write_bytes(payload)
        script = root / "tools"
        script.mkdir()
        (script / "fake-gen.py").write_text(FAKE_GENERATOR)
        config = root / "sources.json"
        entry = {
            "name": package["name"],
            "filename": f"{package['name']}.tar.xz",
            "sha512": hashlib.sha512(payload).hexdigest()
            if package.get("matching", True)
            else "ab" * 64,
            "generate": {"script": "tools/fake-gen.py", "input": "test", "method": "test"},
        }
        if package.get("with_url"):
            entry["url"] = "https://example.org/should-not-be-here.tar.xz"
        config.write_text(json.dumps({"packages": [entry]}))
        return subprocess.run(
            [
                sys.executable,
                str(SOURCE_PIPELINE),
                package["name"],
                "--config",
                str(config),
                "--output",
                str(root / "sources"),
                "--report-dir",
                str(root / "reports"),
                "--stage-into",
                str(root / "packages"),
            ],
            cwd=root,
            capture_output=True,
            text=True,
        )

    def test_generated_source_is_built_verified_and_staged(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            result = self.run_pipeline(root, {"name": "demo-gen"})
            self.assertEqual(result.returncode, 0, result.stderr + result.stdout)
            self.assertEqual(
                (root / "packages" / "demo-gen" / "demo-gen.tar.xz").read_bytes(),
                b"deterministically generated bytes",
            )
            report = (root / "reports" / "demo-gen.json").read_text()
            self.assertIn('"result": "accepted"', report)
            self.assertIn("generated:tools/fake-gen.py", report)

    def test_generated_source_with_wrong_hash_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            result = self.run_pipeline(root, {"name": "demo-gen", "matching": False})
            self.assertEqual(result.returncode, 1)
            self.assertIn("SHA-512 mismatch", result.stdout)
            self.assertFalse((root / "packages" / "demo-gen" / "demo-gen.tar.xz").exists())

    def test_generated_entry_must_not_carry_a_url(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            result = self.run_pipeline(root, {"name": "demo-gen", "with_url": True})
            self.assertEqual(result.returncode, 1)
            self.assertIn("must not carry url", result.stderr + result.stdout)

    def test_missing_generation_script_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            package_dir = root / "packages" / "demo-gen"
            package_dir.mkdir(parents=True)
            config = root / "sources.json"
            config.write_text(
                json.dumps(
                    {
                        "packages": [
                            {
                                "name": "demo-gen",
                                "filename": "demo-gen.tar.xz",
                                "sha512": "ab" * 64,
                                "generate": {"script": "tools/does-not-exist.py"},
                            }
                        ]
                    }
                )
            )
            result = subprocess.run(
                [
                    sys.executable,
                    str(SOURCE_PIPELINE),
                    "demo-gen",
                    "--config",
                    str(config),
                    "--output",
                    str(root / "sources"),
                    "--report-dir",
                    str(root / "reports"),
                ],
                cwd=root,
                capture_output=True,
                text=True,
            )
            self.assertEqual(result.returncode, 1)
            self.assertIn("generation script does not exist", result.stdout)


if __name__ == "__main__":
    unittest.main()
