#!/usr/bin/env python3
"""Create direct-source candidates from imported RPM recipes.

This deliberately does not consult Fedora's lookaside cache. A candidate is
accepted only when the resolved Source0 is an upstream HTTP(S) URL and its
bytes can be downloaded directly. Everything else is reported for an explicit
maintainer decision rather than silently falling back to Rawhide.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools import generated_sources


FEDORA_HOSTS = ("fedoraproject.org", "src.fedoraproject.org", "kojipkgs.fedoraproject.org")


def manifest_pins(package_dir: Path) -> dict[str, str]:
    """Return the SHA-512 pins recorded in a package's Fedora `sources` file."""
    pins = {}
    manifest = package_dir / "sources"
    if manifest.is_file():
        for line in manifest.read_text().splitlines():
            match = re.fullmatch(r"SHA512 \((\S+)\) = ([0-9a-f]{128})", line.strip())
            if match:
                pins[match.group(1)] = match.group(2)
    return pins


GENERATED_SOURCES = generated_sources.GENERATORS


def generated_candidate(package_dir: Path) -> dict:
    """Build the source-lock metadata for a recipe whose Source0 is generated.

    The returned entry has no ``sha512`` yet; :func:`prove_generated` fills it
    with the digest of an actual generation run.
    """
    return generated_sources.metadata_for(package_dir.name, package_dir)


def prove_generated(candidate: dict, package_dir: Path) -> str:
    """Generate the archive twice and return the digest only if both agree.

    A source lock is only as strong as the transformation's determinism, so a
    single run is never accepted. When the package manifest already pins the
    filename, the generated bytes must match that pin -- drift means the
    manifest records Fedora's payload, not ours, and must be repinned first.
    """
    script = Path(__file__).resolve().parent / "generated_sources.py"
    digests = []
    for _ in range(2):
        with tempfile.TemporaryDirectory(prefix="generated-source-") as work:
            subprocess.run(
                [sys.executable, str(script), candidate["name"], str(package_dir), work],
                check=True,
            )
            artifact = Path(work) / candidate["filename"]
            if not artifact.is_file():
                raise ValueError(f"generation did not produce {candidate['filename']}")
            digests.append(generated_sources.sha512_path(artifact))
    if digests[0] != digests[1]:
        raise ValueError(
            f"non-deterministic generation for {candidate['name']}: "
            f"{digests[0]} != {digests[1]}"
        )
    pinned = manifest_pins(package_dir).get(candidate["filename"])
    if pinned and pinned != digests[0]:
        raise ValueError(
            f"generated bytes do not match the manifest pin for {candidate['filename']}: "
            f"manifest has {pinned}, generation produced {digests[0]}; "
            f"repin packages/{candidate['name']}/sources to the generated digest first"
        )
    return digests[0]


def merge_candidates(existing: dict, candidates: list[dict]) -> dict:
    """Append candidates for unlocked packages, never disturbing a lock.

    Existing entries keep their parsed form exactly, so a merge round-trips
    byte-for-byte once JSON-normalized. A candidate naming an already-locked
    package is a conflict, not an update.
    """
    merged = dict(existing)
    packages = list(existing.get("packages", []))
    locked = {entry["name"] for entry in packages}
    seen = set()
    for candidate in candidates:
        name = candidate["name"]
        if name in locked:
            raise ValueError(f"source lock already exists: {name}")
        if name in seen:
            raise ValueError(f"duplicate candidate: {name}")
        seen.add(name)
        packages.append(candidate)
    merged["packages"] = packages
    return merged


def plan_targets(packages: Path, already_supplied: dict, only: str | None = None) -> list[Path]:
    """Select recipe directories to process.

    An explicit ``only`` selection is processed even when Hummingbird already
    supplies the package; the default scan keeps skipping supplied packages.
    """
    available = sorted(path for path in packages.iterdir() if path.is_dir())
    if only is not None:
        selected = [path for path in available if path.name == only]
        if not selected:
            raise ValueError(f"no package recipe named {only}")
        return selected
    return [path for path in available if path.name not in already_supplied]


def rpm_value(spec: Path, query: str) -> str:
    # A spec can emit dozens of binary package records.  Source identity and
    # Version must come from the one SRPM record, not concatenated binary
    # subpackages (for example, libblockdev's plugins).
    return subprocess.check_output(["rpmspec", "-q", "--srpm", "--qf", query, str(spec)], text=True).splitlines()[0]


def sources(spec: Path) -> list[tuple[int, str]]:
    parsed = subprocess.check_output(["rpmspec", "--parse", str(spec)], text=True, stderr=subprocess.STDOUT)
    return [(int(index or 0), url) for index, url in re.findall(r"^Source(\d*):\s*(\S+)\s*$", parsed, flags=re.MULTILINE)]


def sha512(url: str) -> tuple[str, str]:
    request = urllib.request.Request(url, headers={"User-Agent": "utah-packages-bootstrap/1"})
    value = hashlib.sha512()
    with urllib.request.urlopen(request, timeout=120) as response:
        # GitHub release redirects end at an opaque object-store name, and some
        # upstreams have a meaningless path basename -- a crates.io download URL
        # ends in literally "download". RPM takes the local file name from the
        # "#/name" fragment when the URL carries one, and from the declared URL
        # basename otherwise; mirror that so the staged file matches Source0.
        parsed = urllib.parse.urlparse(url)
        filename = parsed.fragment.lstrip("/") or Path(parsed.path).name
        for block in iter(lambda: response.read(1024 * 1024), b""):
            value.update(block)
    return value.hexdigest(), filename


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--packages", type=Path, default=Path("packages"))
    parser.add_argument("--output", type=Path, default=Path("config/upstream-sources.json"))
    parser.add_argument("--report", type=Path, default=Path("reports/direct-source-bootstrap.json"))
    parser.add_argument("--provided-packages", type=Path, help="newline-delimited package names already supplied by Hummingbird")
    parser.add_argument("--provided-sources", type=Path, help="JSON inventory of source packages already supplied by Hummingbird")
    parser.add_argument("--merge", action="store_true",
                        help="merge candidates into the existing output file instead of replacing it")
    parser.add_argument("--package",
                        help="process only this recipe, even if Hummingbird already supplies it")
    args = parser.parse_args()
    root = args.root.resolve()
    packages = (root / args.packages).resolve()
    provided_names = set(args.provided_packages.read_text().split()) if args.provided_packages else set()
    resolution_path = root / "reports/bluefin-rawhide-resolution.json"
    resolution = json.loads(resolution_path.read_text()) if resolution_path.exists() else {}
    requested_by_source: dict[str, set[str]] = {}
    for binary, source in resolution.get("resolved_binary_to_source", {}).items():
        requested_by_source.setdefault(source, set()).add(binary)
    already_supplied = {
        source: sorted(binaries)
        for source, binaries in requested_by_source.items()
        if binaries and binaries <= provided_names
    }
    if args.provided_sources:
        supplied_sources = json.loads(args.provided_sources.read_text()).get("sources", [])
        for source in supplied_sources:
            already_supplied.setdefault(source, sorted(requested_by_source.get(source, [])))
    candidates, rejected = [], []
    for package in plan_targets(packages, already_supplied, only=args.package):
        specs = list(package.glob("*.spec"))
        if len(specs) != 1:
            rejected.append({"package": package.name, "reason": f"expected one spec, found {len(specs)}"})
            continue
        spec = specs[0]
        try:
            if package.name in GENERATED_SOURCES:
                if not args.package:
                    raise ValueError("generated Source0 requires an explicit --package selection")
                metadata = generated_candidate(package)
                digest = prove_generated(metadata, package)
                candidate = {
                    "name": metadata["name"],
                    "version": metadata["version"],
                    "filename": metadata["filename"],
                    "sha512": digest,
                    "generate": metadata["generate"],
                }
                candidates.append(candidate)
                continue
            name, version = rpm_value(spec, "%{NAME}"), rpm_value(spec, "%{VERSION}")
            declared_sources = sources(spec)
            url = next((value for index, value in declared_sources if index == 0), None)
            if not url or not url.startswith(("http://", "https://")):
                raise ValueError("Source0 is not a direct HTTP(S) URL")
            if len(declared_sources) > 1 and not args.package:
                raise ValueError("additional Source entries require an explicit verified source-closure mapping")
            if urllib.parse.urlparse(url).hostname in FEDORA_HOSTS:
                raise ValueError("Source0 points at Fedora infrastructure, not the upstream")
            digest, filename = sha512(url)
            if args.package:
                # An explicit selection asserts that upstream still serves the
                # exact bytes the recipe's Fedora manifest pins for Source0.
                pinned = manifest_pins(package).get(filename)
                if pinned and pinned != digest:
                    raise ValueError(
                        f"upstream bytes for {filename} do not match the pinned manifest: "
                        f"expected {pinned}, got {digest}"
                    )
            candidates.append({"name": name, "version": version, "url": url, "filename": filename, "sha512": digest})
        except Exception as error:
            rejected.append({"package": package.name, "spec": str(spec.relative_to(root)), "reason": str(error)})
    output, report = root / args.output, root / args.report
    output.parent.mkdir(parents=True, exist_ok=True)
    report.parent.mkdir(parents=True, exist_ok=True)
    if args.merge:
        existing = json.loads(output.read_text()) if output.exists() else {"schema": 1, "packages": []}
        payload = merge_candidates(existing, candidates)
    else:
        payload = {"schema": 1, "packages": candidates}
    output.write_text(json.dumps(payload, indent=2) + "\n")
    report.write_text(json.dumps({"accepted": len(candidates), "already_supplied_by_hummingbird": already_supplied,
                                  "rejected": rejected}, indent=2) + "\n")
    print(f"accepted direct sources: {len(candidates)}; already supplied: {len(already_supplied)}; needs explicit mapping: {len(rejected)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
