#!/usr/bin/env python3
"""Deterministic YAML rendering for .packit.yaml across all inventory packages."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tools.package_inventory import inventory, source_locks

HEADER = """# Root-level Packit monorepo config.
# Generated by tools/render_packit_config.py -- do not edit manually.
actions:
  create-archive:
    - bash -c 'python3 "$(git rev-parse --show-toplevel)/tools/packit_source0.py"'
packages:
"""


def render(root: Path) -> str:
    records = inventory(root)
    lock_map = source_locks(root)

    lines = [HEADER.rstrip("\n")]
    for record in sorted(records, key=lambda r: r.name):
        entry = lock_map.get(record.name, {})
        source_name = entry.get("dist_git_name", record.name)
        spec_filename = record.spec.name
        lines.append(f"  {record.name}:")
        lines.append(f"    specfile_path: {spec_filename}")
        lines.append(f"    upstream_package_name: {source_name}")
        lines.append(f"    downstream_package_name: {source_name}")
        lines.append("    paths:")
        lines.append(f"      - packages/{record.name}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write to .packit.yaml")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    rendered = render(root)
    if args.write:
        (root / ".packit.yaml").write_text(rendered)
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
